package edu.yaksha.starPerformer;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.stream.Collectors;
import java.util.stream.Stream;





public class Main 
{
    public static void main( String[] args )
    {
    	Scanner scanner=new Scanner(System.in);
        System.out.println("Enter number of Agents:");
        int no=Integer.parseInt(scanner.nextLine());
        List<Agent> agentList=new ArrayList<Agent>();
        for(int i=0;i<no;i++)
        {
        	System.out.println("Enter Agent name:");
        	String name=scanner.nextLine();
        	System.out.println("Enter Amount of Fund generated by the agent:");
        	long amount=Long.parseLong(scanner.nextLine());
        	Agent agent=new Agent(name,amount);
        	agentList.add(agent);
        }
        Stream<Agent> five=agentList.stream();
        Stream<Agent> three=agentList.stream();
        Stream<Agent> one=agentList.stream();
        List<Agent>fiveStar=five.filter(agent->agent.getGeneratedFund()>=2000000).collect(Collectors.toList());
       // List<Agent>fiveStarList=fiveStar.collect(Collectors.toList());
        List<Agent> threeStar=three.filter(agent->agent.getGeneratedFund()>=1500000 && agent.getGeneratedFund()<2000000).collect(Collectors.toList());
        List<Agent> oneStar=one.filter(agent->agent.getGeneratedFund()>=1000000 && agent.getGeneratedFund()<1500000).collect(Collectors.toList());
        Map<String,String> starMap=new LinkedHashMap<String,String>();
        for(Agent agent:fiveStar)
        {
        	starMap.put(agent.getName(),"*****");
        }
        for(Agent agent:threeStar)
        {
        	starMap.put(agent.getName(),"***");
        }
        for(Agent agent:oneStar)
        {
        	starMap.put(agent.getName(),"*");
        }
        
        System.out.println(starMap);
        
    }
}
